import Head from "next/head";
import Link  from "next/link";
import { Geist_Mono } from "next/font/google";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
   return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className={geistMono.className}>ルートページです。</p>
         <Link href='/about' key='ToAbout' >aboutページへ移動</Link>
      </main>
    </>
  );
}